#!/bin/bash

version="1.3.1"

function print_version {
  echo $version
}

function print_add_usage {
  echo "usage: aliaser add <alias> <command>"
  echo "      The alias name must not contain any spaces"
}

function print_remove_usage {
  echo "usage: aliaser rm <alias>"
  echo "      The alias name must not contain any spaces"
}

function print_help {
  echo "Tool for managing bash/zsh aliases"
  echo
  echo "usage: aliaser <operation>"
  echo
  echo "operations:"
  echo "      ls"
  echo "            Lists all aliases saved in the aliases file, in alphabetical order"
  echo 
  echo "      add <alias> <command>"
  echo "            Creates/replaces an alias for the specified command in the aliases file"
  echo "            The alias name must not contain any spaces, and can only consist of alphanumeric characters"
  echo
  echo "      rm <alias>"
  echo "            Removes the alias permanently from the aliases file"
  echo "            The alias name must not contain any spaces"
  echo
  echo "      help"
  echo "            Prints the help display"
  echo
  echo "      version"
  echo "            Prints the current version"
  echo
  echo "Visit https://github.com/bhayatus/aliaser for details on setup"
}

function list_aliases {
  count=`grep -o "^alias" $alias_file | wc -l`
  if [[ $count -gt 0 ]]; then
    sort $alias_file
  else
    echo "No aliases found in $alias_file"
  fi
}

function add_alias {
  if [[ $alias =~ [^0-9A-Za-z]+ ]]; then
    echo "Alias name can only contain alphanumeric characters"
    exit 1
  fi
  count=`grep -o "^alias $alias=" $alias_file | wc -l`
  if [[ $count -eq 1 ]]; then
    echo "Alias '$alias' already exists, replace? (y to continue)"
    read response
    if [[ $response != "y" ]]; then
      exit
    else
      sed -i.bak "s/^alias $alias=.*$/alias $alias='$command'/g" $alias_file
      rm "$alias_file.bak"
    fi
  else
    echo "alias $alias='$command'" >> $alias_file
  fi

  echo "Added alias '$alias' for command '$command'"
}

function remove_alias {
  count=`grep -o "^alias $alias=" $alias_file | wc -l`
  if [[ $count -eq 0 ]]; then
    echo "No alias named '$alias' found in $alias_file"
    exit 1
  fi

  sed -i.bak "/^alias $alias=/d" $alias_file
  rm "$alias_file.bak"

  echo "Removed alias '$alias'"
}

function main {
  if [ $# -eq 0 ]; then
    print_help
    exit 1
  fi

  if [[ -z ${ALIASES_FILE} ]]; then
    echo "ALIASES_FILE environment variable must be set"
    exit 1
  else
    alias_file=${ALIASES_FILE}
  fi

  operation=""
  alias=""
  command=""

  arg_pos=1
  for i in $@; do
    if [[ $arg_pos -eq 1 ]]; then
      operation=$i
    fi
    if [[ $arg_pos -eq 2 ]]; then
      alias=$i
    fi
    if [[ $arg_pos -eq 3 ]]; then
      command=$i
    fi
    if [[ $arg_pos -gt 3 ]]; then
      command="${command} ${i}"
    fi
    ((arg_pos=arg_pos+1))
  done

  case $operation in
    "ls")
      list_aliases
      ;;
    "add")
      if [[ $# -lt 3 || $alias =~ " " ]]; then
        print_add_usage
        exit 1
      fi
      add_alias $alias $command
      ;;
    "rm")
      if [[ $# -ne 2 || $alias =~ " " ]]; then
        print_remove_usage
        exit 1
      fi
      remove_alias $alias
      ;;
    "version")
      print_version
      ;;
    "help")
      print_help
      ;;
    *)
      print_help
      ;;
  esac
}

main $@